Update main.yml
re-trying with pytest

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,34 +20,55 @@ jobs:
         os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
         python-version: ['3.7', '3.6']
     steps:
-      - name: Install Dependencies
-      - uses: conda-incubator/setup-miniconda@v2
-        with:
-          activate-environment: qfit
-          enviornment-file: environment.yml
-          auto-activate-base: false
-          python-version: ${{ matrix.python-version }}
-      - name: Checkout qfit
-        uses: actions/checkout@v2
-      - name: Install qfit
-        working-directory: .
-        shell: bash -l -eo pipefail {0}
-        run: |
-          pip install .
-          conda install --yes tox-conda #can we just put this into environment? 
-      - name: Describe qfit environment
-        shell: bash -l -eo pipefail {0}
-        run: |
-          # Read conda environment variables
+    - uses: actions/checkout@v1
+    - name: Update Conda environment with "environment.yml"
+      uses: matthewrmshin/conda-action@v1
+      with:
+        args: conda env update -f ./enviornment.yml
+    - name: Run "pytest" with the Conda environment
+      uses: matthewrmshin/conda-action@v1
+      with:
+        args: pytest
+
+
+#jobs:
+#  test:
+#    name: Build & run tests (${{ matrix.python-version }}, ${{ matrix.os }})
+#    runs-on: ${{ matrix.os }}
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
+#        python-version: ['3.7', '3.6']
+#    steps:
+#      - name: Install Dependencies
+#      - uses: conda-incubator/setup-miniconda@v2
+#        with:
+#          activate-environment: qfit
+#          enviornment-file: environment.yml
+#          auto-activate-base: false
+#          python-version: ${{ matrix.python-version }}
+#      - name: Checkout qfit
+#       uses: actions/checkout@v2
+#      - name: Install qfit
+#        working-directory: .
+#        shell: bash -l -eo pipefail {0}
+#        run: |
+#          pip install .
+#          conda install --yes tox-conda #can we just put this into environment? 
+#      - name: Describe qfit environment
+#        shell: bash -l -eo pipefail {0}
+#        run: |
+#          # Read conda environment variables
           # How is conda configured?
-          conda info
+ #         conda info
           # Read channels priority
           #conda config --show channels
           # Which packages are installed?
-          conda list
-      - name: TEST (Basic) Check qfit_protein can execute (test --help)
-        shell: bash -l {0}
-        run: qfit_protein --help
-      - name: TEST (Full) Thoroughly test qFit with tox
-        shell: bash -l -o pipefail {0}
-        run: tox -e py
+#          conda list
+#      - name: TEST (Basic) Check qfit_protein can execute (test --help)
+#        shell: bash -l {0}
+#        run: qfit_protein --help
+ #     - name: TEST (Full) Thoroughly test qFit with tox
+ #       shell: bash -l -o pipefail {0}
+ #       run: tox -e py
